### PR TITLE
Move to util

### PR DESCRIPTION
**Pull request by c0c0n3**
This PR fully implements #9.

### CODE REVIEW

**Comment by jburel** [comment]
Also build locally
```

BUILD SUCCESSFUL

Total time: 15 mins 20.709 secs
```

Discussed with @c0c0n3 today, merging this PR so he can continue with the refactoring
2 more PR to come then we will tag to 0.3

**Comment by joshmoore** [comment]
Not sure what the content of the discussion is/was, but I'm concerned about the use of `util.*` as a package.

**Comment by c0c0n3** [comment]
yip, and there's more...wait to see the new `kew.*` packages I'm going to merge in next week :-)
But, honestly, I wouldn't stress about it. As soon as we decide on namespaces, I'll run a big-hammer refactoring task to rename the root packages. Basically a no-brainer, but I don't want to do it twice which is why I'm holding off until we know for sure what those namespaces are going be...

**Comment by c0c0n3** [comment]
Closes #9

**Pull request merged**
