### PR TITLE
Copy over Smuggler v1.0.0 code base.

### PR DESCRIPTION
**Pull request by c0c0n3**
This repo starts as an exact copy of Smuggler's code base at tag v1.0.0:
- https://github.com/c0c0n3/ome-smuggler/tree/v1.0.0

### CODE REVIEW

**Comment by jburel** [comment]
I have enabled travis on this repo

**Comment by joshmoore** [comment]
@jburel @c0c0n3 : are there any plans re: versions for this repo? From my side, I was thinking:

 * 0.1.0: the original smuggler 1.0.0 but refactored
 * 0.2.0: first PRs, etc

but I could also imagine:

 * 0.1.0: original smuggler 1.0.0 (no changes)
 * 0.2.0: renames, etc.

cc: @sbesson

**Comment by jburel** [comment]
v1.0.0 is the working version in Montpellier (if I am not mistaken)
That's the one I was thinking as the starting point i.e. 0.1.0 and then start refactoring from there.
Let's have a quick chat this am

**Comment by c0c0n3** [comment]
@jburel @joshmoore @sbesson : I think it's best to hold off on versioning for now, especially if we want to use [semantic versioning][sem-ver]. In fact, I'll be hacking this thing to pieces (literally!) over the next couple of weeks, so if we followed the semantic versioning guidelines we'd have to use *major* version numbers even for a namespace change if that affects public APIs. So yah, let's have a chat about it later.

[sem-ver]: http://semver.org/

**Comment by joshmoore** [comment]
> I think it's best to hold off on versioning for now, especially if we want to use semantic versioning.

Partially disagree. http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase i.e. as soon as we have something we want to _use_ anywhere, let's call that 0.1.0.

> In fact, I'll be hacking this thing to pieces (literally!) over the next couple of weeks,

Guess as long as it's fairly time-boxed, that's fine. But I consider having a `0.1.0` soon quite a good thing.

> if we followed the semantic versioning guidelines we'd have to use major version numbers even for a namespace change

Not during sub-1.

An alternative (suggested by @sbesson) would be to consider this state as 0.0.1 and then your first refactoring is 0.1.0.

**Comment by jburel** [comment]
Discussed via zoom with @c0c0n3 @joshmoore and @sbesson, merging and tagging to 0.1.0

**Pull request merged**
